version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: brain_tumor_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_admin123
      MYSQL_DATABASE: brain_tumor_db
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  web:
    build: .
    image: abhay41/brain_tumor_app:latest
    container_name: brain_tumor_web
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./app/static/uploads:/app/static/uploads
    depends_on:
      - mysql
    networks:
      - backend
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "run:app"]

  nginx:
    image: nginx:latest
    container_name: brain_tumor_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/static:ro
    depends_on:
      - web
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
