# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: brain-tumor-app
spec:
  storageClassName: standard   # Changed from manual to standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: brain-tumor-app
spec:
  storageClassName: standard   # Changed from manual to standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi