# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: brain-tumor-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9hZG1pbjEyMw==  # root_admin123
  SECRET_KEY: VGhpcyBpcyBBYmhheQ==          # "This is Abhay"
  MYSQL_PASSWORD: cm9vdF9hZG1pbjEyMw==      # root_admin123