# volumes.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: brain-tumor-app
spec:
  storageClassName: standard  # Changed from manual to standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
  namespace: brain-tumor-app
spec:
  storageClassName: standard   # Changed from manual to standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/uploads"
    type: DirectoryOrCreate